// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetAutoSave():Promise<boolean>;

export function GetConnectionStatus():Promise<main.ConnectionStatus>;

export function GetDeviceInfo():Promise<main.DeviceInfo>;

export function GetSaveDirectory():Promise<string>;

export function GetSubscriptionConfig():Promise<main.SubscriptionConfig>;

export function RequestSnapshot():Promise<void>;

export function SaveFrameToFile(arg1:string,arg2:string):Promise<main.SaveResult>;

export function SelectSaveDirectory():Promise<string>;

export function SetAutoSave(arg1:boolean):Promise<void>;

export function SetSaveDirectory(arg1:string):Promise<void>;

export function Subscribe():Promise<void>;

export function SubscribeWithConfig(arg1:main.SubscriptionConfig):Promise<void>;

export function TriggerCapture(arg1:number):Promise<void>;

export function Unsubscribe():Promise<void>;
