// SPDX-License-Identifier: Proprietary
// Copyright (c) 2026 Pumatronix
//
// AUTO-GENERATED FILE -- DO NOT EDIT.
// Regenerate with `make codegen` (see tools/codegen/README.md).
//
// Generated from an OpenAPI 3.0 snapshot of the ITSCAM camera webapp.
// Edit tools/codegen/codegen.mjs and rerun, do not patch this output.
// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do one of these:
//
//    using Pumatronix.Itscam.RestTypes;
//
//    var profileConfig = ProfileConfig.FromJson(jsonString);
//    var ocrConfig = OcrConfig.FromJson(jsonString);
//    var analyticsConfig = AnalyticsConfig.FromJson(jsonString);
//    var classifierConfig = ClassifierConfig.FromJson(jsonString);
//    var autoFocus = AutoFocus.FromJson(jsonString);
//    var streamConfig = StreamConfig.FromJson(jsonString);
//    var misc = Misc.FromJson(jsonString);
//    var miscVolatile = MiscVolatile.FromJson(jsonString);
//    var itscamproConfig = ItscamproConfig.FromJson(jsonString);
//    var itscamproStatus = ItscamproStatus.FromJson(jsonString);
//    var imageSignConfig = ImageSignConfig.FromJson(jsonString);
//    var ftpConfig = FtpConfig.FromJson(jsonString);
//    var linceConfig = LinceConfig.FromJson(jsonString);
//    var linceStatus = LinceStatus.FromJson(jsonString);
//    var vehicleIndicatorConfig = VehicleIndicatorConfig.FromJson(jsonString);
//    var protocolsConfig = ProtocolsConfig.FromJson(jsonString);
//    var profileTransitioner = ProfileTransitioner.FromJson(jsonString);
//    var lanesConfig = LanesConfig.FromJson(jsonString);
//    var ioConfig = IoConfig.FromJson(jsonString);
//    var ioBasic = IoBasic.FromJson(jsonString);
//    var restApiClientConfig = RestApiClientConfig.FromJson(jsonString);
//    var restApiClientStatus = RestApiClientStatus.FromJson(jsonString);
//    var licenses = Licenses.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace Pumatronix.Itscam.RestTypes
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// Camera profile configuration
    /// </summary>
    public partial class ProfileConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("active")]
        public bool? Active { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("advanced")]
        public Advanced Advanced { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("color")]
        public Color Color { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("description")]
        [JsonConverter(typeof(PurpleMinMaxLengthCheckConverter))]
        public string Description { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("exposure")]
        public Exposure Exposure { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("hdr")]
        public Hdr Hdr { get; set; }

        [JsonPropertyName("id")]
        public long Id { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("lens")]
        public ProfileConfigLens Lens { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("movFilter")]
        public MovFilter MovFilter { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("multipleExposures")]
        public MultipleExposures MultipleExposures { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("name")]
        [JsonConverter(typeof(FluffyMinMaxLengthCheckConverter))]
        public string Name { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("overlay")]
        public Overlay Overlay { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("transitions")]
        public Transitions Transitions { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("trigger")]
        public Trigger Trigger { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("whitebalance")]
        public ProfileConfigWhitebalance Whitebalance { get; set; }
    }

    public partial class Advanced
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("exposition")]
        public Exposition Exposition { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("iris")]
        public AdvancedIris Iris { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("whitebalance")]
        public AdvancedWhitebalance Whitebalance { get; set; }
    }

    public partial class Exposition
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("preferredShutter")]
        public long? PreferredShutter { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("updateFactor")]
        public double? UpdateFactor { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("updateRate")]
        public long? UpdateRate { get; set; }
    }

    public partial class AdvancedIris
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("updateRate")]
        public long? UpdateRate { get; set; }
    }

    public partial class AdvancedWhitebalance
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("updateRate")]
        public long? UpdateRate { get; set; }
    }

    /// <summary>
    /// Camera color configuration fields
    /// </summary>
    public partial class Color
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("blacklevel")]
        public long? Blacklevel { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("brightness")]
        public long? Brightness { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("contrast")]
        public long? Contrast { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("gain")]
        public WhitebalanceClass Gain { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("gamma")]
        public long? Gamma { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("saturation")]
        public long? Saturation { get; set; }
    }

    /// <summary>
    /// Single RGB value in float format
    /// </summary>
    public partial class WhitebalanceClass
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("blue")]
        public double? Blue { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("green")]
        public double? Green { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("red")]
        public double? Red { get; set; }
    }

    /// <summary>
    /// Camera exposure configuration fields
    /// </summary>
    public partial class Exposure
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("gain")]
        public ShutterClass Gain { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("iris")]
        public ExposureIris Iris { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("level")]
        public Level Level { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("shutter")]
        public ShutterClass Shutter { get; set; }
    }

    /// <summary>
    /// Shutter attributes
    /// </summary>
    public partial class ShutterClass
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("automatic")]
        public bool? Automatic { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("fixedValue")]
        public long? FixedValue { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("maxValue")]
        public long? MaxValue { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("minValue")]
        public long? MinValue { get; set; }
    }

    public partial class ExposureIris
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("automatic")]
        public bool? Automatic { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("fixedValue")]
        public long? FixedValue { get; set; }
    }

    public partial class Level
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("holdTime")]
        public long? HoldTime { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mode")]
        public Mode? Mode { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("roi")]
        public Roi1Class Roi { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("targetValue")]
        public double? TargetValue { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("updateRate")]
        public long? UpdateRate { get; set; }
    }

    public partial class Roi1Class
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x0")]
        public long? X0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x1")]
        public long? X1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x2")]
        public long? X2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x3")]
        public long? X3 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y0")]
        public long? Y0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y1")]
        public long? Y1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y2")]
        public long? Y2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y3")]
        public long? Y3 { get; set; }
    }

    public partial class Hdr
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enable")]
        public bool? Enable { get; set; }
    }

    /// <summary>
    /// Camera lens configuration fields
    /// </summary>
    public partial class ProfileConfigLens
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("exchanger")]
        public bool? Exchanger { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("focus")]
        public long? Focus { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("zfMirrorProfile0")]
        public bool? ZfMirrorProfile0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("zoom")]
        public long? Zoom { get; set; }
    }

    public partial class MovFilter
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("onlyCheck")]
        public bool? OnlyCheck { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("roi")]
        public Roi1Class Roi { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("threshold")]
        public double? Threshold { get; set; }
    }

    public partial class MultipleExposures
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("settings")]
        public List<Something> Settings { get; set; }
    }

    /// <summary>
    /// Multiple exposures configuration
    /// </summary>
    public partial class Something
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("flash")]
        public Flash Flash { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("gain")]
        public SettingGain Gain { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("shutter")]
        public Shutter Shutter { get; set; }
    }

    /// <summary>
    /// Camera flash configuration
    /// </summary>
    public partial class Flash
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("power")]
        public List<Power> Power { get; set; }
    }

    public partial class Power
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("out")]
        public long? Out { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("percent")]
        public long? Percent { get; set; }
    }

    public partial class SettingGain
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("percentageOfCurrent")]
        public bool? PercentageOfCurrent { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("value")]
        public double? Value { get; set; }
    }

    public partial class Shutter
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("percentageOfCurrent")]
        public bool? PercentageOfCurrent { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("value")]
        public double? Value { get; set; }
    }

    public partial class Overlay
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enable")]
        public bool? Enable { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("text")]
        public string Text { get; set; }
    }

    /// <summary>
    /// Camera profile transition configuration
    /// </summary>
    public partial class Transitions
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("lower")]
        public Lower Lower { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("upper")]
        public Lower Upper { get; set; }
    }

    public partial class Lower
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("endTime")]
        public string EndTime { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("holdTime")]
        public long? HoldTime { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("level")]
        public double? Level { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("profile")]
        public long? Profile { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("startTime")]
        public string StartTime { get; set; }
    }

    public partial class Trigger
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("event")]
        public string Event { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("minimumInterval")]
        public long? MinimumInterval { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("port")]
        public long? Port { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("roi")]
        public Roi1Class Roi { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("threshold")]
        public double? Threshold { get; set; }
    }

    /// <summary>
    /// Camera white balance configuration fields
    /// </summary>
    public partial class ProfileConfigWhitebalance
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("automatic")]
        public bool? Automatic { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("weights")]
        public WhitebalanceClass Weights { get; set; }
    }

    /// <summary>
    /// Ocr service configuration
    /// </summary>
    public partial class OcrConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ocr")]
        public OcrConfigOcr Ocr { get; set; }
    }

    public partial class OcrConfigOcr
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("avgCharHeight")]
        public long? AvgCharHeight { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("avgPlateAngle")]
        public double? AvgPlateAngle { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("avgPlateSlant")]
        public double? AvgPlateSlant { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("classifierExpansion")]
        public double? ClassifierExpansion { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("countryCode")]
        public long? CountryCode { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("licensed")]
        public bool? Licensed { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("maxCharHeight")]
        public long? MaxCharHeight { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("maxLowProbChars")]
        public long? MaxLowProbChars { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("maxPlates")]
        public long? MaxPlates { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("minCharHeight")]
        public long? MinCharHeight { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("minProbPerChar")]
        public double? MinProbPerChar { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("processingMode")]
        public long? ProcessingMode { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("processingQueue")]
        public long? ProcessingQueue { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("processingThreads")]
        public long? ProcessingThreads { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("processingTimeout")]
        public long? ProcessingTimeout { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("roi")]
        public Roi1Class Roi { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("useClassifierResult")]
        public bool? UseClassifierResult { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("vehicleType")]
        public long? VehicleType { get; set; }
    }

    /// <summary>
    /// Plate Analytics service configuration
    /// </summary>
    public partial class AnalyticsConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("voting")]
        public Voting Voting { get; set; }
    }

    public partial class Voting
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("forwardWithoutPlateIfTracker")]
        public bool? ForwardWithoutPlateIfTracker { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("keepBestOnly")]
        public bool? KeepBestOnly { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("maxDiffChars")]
        public long? MaxDiffChars { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("roi1")]
        public Roi1Class Roi1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("roi2")]
        public Roi1Class Roi2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("samePlateDebounce")]
        public long? SamePlateDebounce { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("useClassifier")]
        public bool? UseClassifier { get; set; }
    }

    /// <summary>
    /// Vehicle Classifier service configuration
    /// </summary>
    public partial class ClassifierConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("classifier")]
        public ClassifierConfigClassifier Classifier { get; set; }
    }

    public partial class ClassifierConfigClassifier
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enableCharacteristics")]
        public bool? EnableCharacteristics { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enableSpeed")]
        public bool? EnableSpeed { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("firstOnly")]
        public bool? FirstOnly { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("licensed")]
        public bool? Licensed { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("minProbability")]
        public double? MinProbability { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("modelType")]
        public long? ModelType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("processingQueue")]
        public long? ProcessingQueue { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("processingThreads")]
        public long? ProcessingThreads { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sceneType")]
        public long? SceneType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("speedCalibrationRegion1")]
        public SpeedCalibrationRegion1 SpeedCalibrationRegion1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("speedCalibrationRegion2")]
        public SpeedCalibrationRegion1 SpeedCalibrationRegion2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("triggerEnabled")]
        public bool? TriggerEnabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("triggerRegion0")]
        public TriggerRegion0 TriggerRegion0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("triggerRegion1")]
        public TriggerRegion0 TriggerRegion1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("triggerRegion2")]
        public TriggerRegion0 TriggerRegion2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("triggerRegion3")]
        public TriggerRegion0 TriggerRegion3 { get; set; }
    }

    /// <summary>
    /// Classifier based speed calibration region;
    /// </summary>
    public partial class SpeedCalibrationRegion1
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("p0top1sz")]
        public double? P0Top1Sz { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x0")]
        public long? X0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x1")]
        public long? X1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x2")]
        public long? X2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y0")]
        public long? Y0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y1")]
        public long? Y1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y2")]
        public long? Y2 { get; set; }
    }

    /// <summary>
    /// Classifier based trigger region; * dir: top-bottom, bottom-top, disabled
    /// </summary>
    public partial class TriggerRegion0
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dir")]
        public string Dir { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x0")]
        public long? X0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x1")]
        public long? X1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y0")]
        public long? Y0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y1")]
        public long? Y1 { get; set; }
    }

    /// <summary>
    /// AutoFocus configs
    /// </summary>
    public partial class AutoFocus
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("coarseStep")]
        public long? CoarseStep { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("contrastThreshold")]
        public double? ContrastThreshold { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("roi")]
        public AutoFocusRoi Roi { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("run")]
        public bool? Run { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("updateRate")]
        public long? UpdateRate { get; set; }
    }

    public partial class AutoFocusRoi
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("centerX")]
        public long? CenterX { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("centerY")]
        public long? CenterY { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("height")]
        public long? Height { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("width")]
        public long? Width { get; set; }
    }

    /// <summary>
    /// Stream(s) configuration of device
    /// </summary>
    public partial class StreamConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("h264")]
        public H264 H264 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mjpeg")]
        public Mjpeg Mjpeg { get; set; }
    }

    public partial class H264
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("available")]
        public bool? Available { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("encoder_type")]
        public string EncoderType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("main")]
        public H264Main Main { get; set; }
    }

    /// <summary>
    /// Single h26x stream configuration
    /// </summary>
    public partial class H264Main
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("available")]
        public bool? Available { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("bitrate")]
        public long? Bitrate { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("controlRate")]
        public string ControlRate { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("gop")]
        public long? Gop { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("profile")]
        public string Profile { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("running")]
        public bool? Running { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("source")]
        public string Source { get; set; }
    }

    public partial class Mjpeg
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("available")]
        public bool? Available { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("main")]
        public MjpegMain Main { get; set; }
    }

    /// <summary>
    /// Single MJPEG stream configuration
    /// </summary>
    public partial class MjpegMain
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("available")]
        public bool? Available { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("framerate")]
        public double? Framerate { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("quality")]
        public long? Quality { get; set; }
    }

    /// <summary>
    /// Miscellaneous configs
    /// </summary>
    public partial class Misc
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("cameraOrientation")]
        public bool? CameraOrientation { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("irisHint")]
        public string IrisHint { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("jpegQuality")]
        public long? JpegQuality { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("legacyTsyncGpio")]
        public long? LegacyTsyncGpio { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("scenario1Crop")]
        public Scenario1Crop Scenario1Crop { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("scenario1Overlay")]
        public string Scenario1Overlay { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("scenario1OverlayTextSize")]
        public long? Scenario1OverlayTextSize { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("scenario2Crop")]
        public Scenario2Crop Scenario2Crop { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("scenario2Overlay")]
        public string Scenario2Overlay { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("scenario2OverlayTextSize")]
        public long? Scenario2OverlayTextSize { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("scenarioOverlayColor")]
        public string ScenarioOverlayColor { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("snapshotCrop")]
        public SnapshotCrop SnapshotCrop { get; set; }
    }

    public partial class Scenario1Crop
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x0")]
        public long? X0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x1")]
        public long? X1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y0")]
        public long? Y0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y1")]
        public long? Y1 { get; set; }
    }

    public partial class Scenario2Crop
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x0")]
        public long? X0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x1")]
        public long? X1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y0")]
        public long? Y0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y1")]
        public long? Y1 { get; set; }
    }

    public partial class SnapshotCrop
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enable")]
        public bool? Enable { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mode")]
        public string Mode { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x0")]
        public long? X0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x1")]
        public long? X1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y0")]
        public long? Y0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y1")]
        public long? Y1 { get; set; }
    }

    /// <summary>
    /// Current Miscellaneous Read-Only configs
    /// </summary>
    public partial class MiscVolatile
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ae")]
        public Ae Ae { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("fps")]
        public Fps Fps { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("gps")]
        public Gps Gps { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("isp")]
        public Isp Isp { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("lens")]
        public MiscVolatileLens Lens { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("profile")]
        public Profile Profile { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("whitebalance")]
        public WhitebalanceClass Whitebalance { get; set; }
    }

    public partial class Ae
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ctrlMode")]
        public string CtrlMode { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("lastRun")]
        public long? LastRun { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("level")]
        public double? Level { get; set; }
    }

    public partial class Fps
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mjpeg")]
        public double? Mjpeg { get; set; }
    }

    public partial class Gps
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("altitude")]
        public double? Altitude { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("available")]
        public bool? Available { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("bearing")]
        public double? Bearing { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dop")]
        public double? Dop { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("fix")]
        public string Fix { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("latitude")]
        public double? Latitude { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("longitude")]
        public double? Longitude { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("numSatellites")]
        public long? NumSatellites { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("secondsSinceLastFix")]
        public long? SecondsSinceLastFix { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("speed")]
        public double? Speed { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("time")]
        public long? Time { get; set; }
    }

    public partial class Isp
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("freeBuffers")]
        public long? FreeBuffers { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("gain")]
        public long? Gain { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("iris")]
        public long? Iris { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("irisModel")]
        public string IrisModel { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("shutter")]
        public long? Shutter { get; set; }
    }

    public partial class MiscVolatileLens
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("focus")]
        public long? Focus { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("zoom")]
        public long? Zoom { get; set; }
    }

    public partial class Profile
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("id")]
        public long? Id { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("name")]
        [JsonConverter(typeof(TentacledMinMaxLengthCheckConverter))]
        public string Name { get; set; }
    }

    /// <summary>
    /// ITSCAMPRO service configuration
    /// </summary>
    public partial class ItscamproConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("itscampro")]
        public Itscampro Itscampro { get; set; }
    }

    public partial class Itscampro
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("address")]
        public string Address { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("debug")]
        public bool? Debug { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enable")]
        public bool? Enable { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("port")]
        public long? Port { get; set; }
    }

    /// <summary>
    /// ITSCAMPRO service status
    /// </summary>
    public partial class ItscamproStatus
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("status")]
        public string Status { get; set; }
    }

    /// <summary>
    /// ImageSign service configuration
    /// </summary>
    public partial class ImageSignConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sign")]
        public Sign Sign { get; set; }
    }

    public partial class Sign
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("appendMode")]
        public string AppendMode { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("loaded")]
        public bool? Loaded { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("update")]
        public bool? Update { get; set; }
    }

    /// <summary>
    /// FTP service configuration
    /// </summary>
    public partial class FtpConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ftp")]
        public Ftp Ftp { get; set; }
    }

    public partial class Ftp
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("address")]
        public string Address { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("anonymous")]
        public bool? Anonymous { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enable")]
        public bool? Enable { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("filename")]
        public string Filename { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("local")]
        public Local Local { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("password")]
        public string Password { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("port")]
        public long? Port { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("protocol")]
        public string Protocol { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("quality")]
        public long? Quality { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("transfer")]
        public Transfer Transfer { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("username")]
        public string Username { get; set; }
    }

    public partial class Local
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("bufferSizeKb")]
        public long? BufferSizeKb { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ttl")]
        public long? Ttl { get; set; }
    }

    public partial class Transfer
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("pollInterval")]
        public long? PollInterval { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("timeout")]
        public long? Timeout { get; set; }
    }

    /// <summary>
    /// Lince service configuration
    /// </summary>
    public partial class LinceConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("authCode")]
        public string AuthCode { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("clientEndpoint")]
        public string ClientEndpoint { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("clientId")]
        public string ClientId { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("environment")]
        public string Environment { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sendRecsNone")]
        public bool? SendRecsNone { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("timeoutResponse")]
        public long? TimeoutResponse { get; set; }
    }

    /// <summary>
    /// Lince service status
    /// </summary>
    public partial class LinceStatus
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("linceStatus")]
        public string LinceStatusLinceStatus { get; set; }
    }

    /// <summary>
    /// VehicleIndicator service configuration
    /// </summary>
    public partial class VehicleIndicatorConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("vehicleIndicator")]
        public VehicleIndicator VehicleIndicator { get; set; }
    }

    public partial class VehicleIndicator
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("vehicleCounterActiveHigh")]
        public bool? VehicleCounterActiveHigh { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("vehicleCounterEnabled")]
        public bool? VehicleCounterEnabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("vehicleCounterGpio")]
        public long? VehicleCounterGpio { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("vehicleCounterPulseWidthMs")]
        public long? VehicleCounterPulseWidthMs { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("vehicleCounterType")]
        public long? VehicleCounterType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("vehicleCounterUdpPort")]
        public long? VehicleCounterUdpPort { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("vehicleCounterUdpSampleTimeMs")]
        public long? VehicleCounterUdpSampleTimeMs { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("vehicleCounterUdpServer")]
        public string VehicleCounterUdpServer { get; set; }
    }

    /// <summary>
    /// Protocols configurations
    /// </summary>
    public partial class ProtocolsConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("configCgi")]
        public ConfigCgi ConfigCgi { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("cougar")]
        public Cougar Cougar { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("itscamprotocol")]
        public Itscamprotocol Itscamprotocol { get; set; }
    }

    public partial class ConfigCgi
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("blockAPI")]
        public bool? BlockApi { get; set; }
    }

    public partial class Cougar
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("auth")]
        public Auth Auth { get; set; }
    }

    public partial class Auth
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("password")]
        public string Password { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("require")]
        public bool? Require { get; set; }
    }

    public partial class Itscamprotocol
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("legacyMode")]
        public bool? LegacyMode { get; set; }
    }

    /// <summary>
    /// Profile Transitioner configs
    /// </summary>
    public partial class ProfileTransitioner
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("automatic")]
        public bool? Automatic { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("levelSmoothing")]
        public string LevelSmoothing { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("resetProfiles")]
        public string ResetProfiles { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("smoothingTime")]
        public long? SmoothingTime { get; set; }
    }

    /// <summary>
    /// Lanes configuration
    /// </summary>
    public partial class LanesConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("region0")]
        public Region0 Region0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("region1")]
        public Region0 Region1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("region2")]
        public Region0 Region2 { get; set; }
    }

    /// <summary>
    /// Lane region
    /// </summary>
    public partial class Region0
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x0")]
        public long? X0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x1")]
        public long? X1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x2")]
        public long? X2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("x3")]
        public long? X3 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y0")]
        public long? Y0 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y1")]
        public long? Y1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y2")]
        public long? Y2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("y3")]
        public long? Y3 { get; set; }
    }

    /// <summary>
    /// Configuration for a specific IO
    /// </summary>
    public partial class IoConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("canFlash")]
        public bool? CanFlash { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("canTrigger")]
        public bool? CanTrigger { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("earlyUs")]
        public long? EarlyUs { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("group")]
        public string Group { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("identifier")]
        public string Identifier { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("isInput")]
        public bool? IsInput { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("isOn")]
        public bool? IsOn { get; set; }

        [JsonPropertyName("port")]
        public long Port { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("protection")]
        public string Protection { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("type")]
        public string Type { get; set; }
    }

    /// <summary>
    /// Simplified information for a specific IO
    /// </summary>
    public partial class IoBasic
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("isInput")]
        public bool? IsInput { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("isOn")]
        public bool? IsOn { get; set; }

        [JsonPropertyName("port")]
        public long Port { get; set; }
    }

    /// <summary>
    /// REST API Client service configuration
    /// </summary>
    public partial class RestApiClientConfig
    {
        [JsonPropertyName("body")]
        public Body Body { get; set; }

        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        [JsonPropertyName("headers")]
        public List<Header> Headers { get; set; }

        [JsonPropertyName("jpeg")]
        public Jpeg Jpeg { get; set; }

        [JsonPropertyName("method")]
        public Method Method { get; set; }

        [JsonPropertyName("persistency")]
        public Persistency Persistency { get; set; }

        [JsonPropertyName("retries")]
        public long Retries { get; set; }

        [JsonPropertyName("sendIndividualRequests")]
        public bool SendIndividualRequests { get; set; }

        [JsonPropertyName("sendWithoutOcr")]
        public bool SendWithoutOcr { get; set; }

        [JsonPropertyName("timeout")]
        public long Timeout { get; set; }

        [JsonPropertyName("url")]
        public Url Url { get; set; }
    }

    public partial class Body
    {
        [JsonPropertyName("parts")]
        public List<Part> Parts { get; set; }

        [JsonPropertyName("variant")]
        public Variant Variant { get; set; }
    }

    public partial class Part
    {
        [JsonPropertyName("content")]
        public string Content { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }
    }

    public partial class Header
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("value")]
        public string Value { get; set; }
    }

    public partial class Jpeg
    {
        [JsonPropertyName("quality")]
        public long Quality { get; set; }

        [JsonPropertyName("resolution")]
        public Resolution Resolution { get; set; }
    }

    public partial class Resolution
    {
        [JsonPropertyName("height")]
        public long Height { get; set; }

        [JsonPropertyName("width")]
        public long Width { get; set; }
    }

    public partial class Persistency
    {
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        [JsonPropertyName("maxDiskUsage")]
        public long MaxDiskUsage { get; set; }

        [JsonPropertyName("maxFileAge")]
        public long MaxFileAge { get; set; }

        [JsonPropertyName("newestFirst")]
        public bool NewestFirst { get; set; }
    }

    public partial class Url
    {
        [JsonPropertyName("host")]
        public string Host { get; set; }

        [JsonPropertyName("path")]
        public string Path { get; set; }

        [JsonPropertyName("query")]
        public List<string> Query { get; set; }

        [JsonPropertyName("scheme")]
        public Scheme Scheme { get; set; }
    }

    /// <summary>
    /// REST API Client service status
    /// </summary>
    public partial class RestApiClientStatus
    {
        [JsonPropertyName("code")]
        public long Code { get; set; }

        [JsonPropertyName("diskUsage")]
        public long DiskUsage { get; set; }

        [JsonPropertyName("fileCount")]
        public long FileCount { get; set; }

        [JsonPropertyName("message")]
        public string Message { get; set; }
    }

    /// <summary>
    /// License service information
    /// </summary>
    public partial class Licenses
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("analytics")]
        public Analytics Analytics { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("deviceId")]
        public DeviceId DeviceId { get; set; }
    }

    public partial class Analytics
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("classifier")]
        public AnalyticsClassifier Classifier { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ocr")]
        public AnalyticsOcr Ocr { get; set; }
    }

    public partial class AnalyticsClassifier
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("customer")]
        public string Customer { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("maxConnections")]
        public long? MaxConnections { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("maxThreads")]
        public long? MaxThreads { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("serial")]
        public string Serial { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sha1")]
        public string Sha1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("state")]
        public long? State { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ttl")]
        public long? Ttl { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("version")]
        public string Version { get; set; }
    }

    public partial class AnalyticsOcr
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("customer")]
        public string Customer { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("maxConnections")]
        public long? MaxConnections { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("maxThreads")]
        public long? MaxThreads { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("serial")]
        public string Serial { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sha1")]
        public string Sha1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("state")]
        public long? State { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ttl")]
        public long? Ttl { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("version")]
        public string Version { get; set; }
    }

    public partial class DeviceId
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("serial")]
        public string Serial { get; set; }
    }

    public enum Mode { Disabled, Fast, Normal, Slow };

    public enum TypeEnum { Json };

    public enum Variant { Multipart, Singlepart };

    public enum Method { Get, Post, Put };

    public enum Scheme { Http, Https };

    public partial class ProfileConfig
    {
        public static ProfileConfig FromJson(string json) => JsonSerializer.Deserialize<ProfileConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class OcrConfig
    {
        public static OcrConfig FromJson(string json) => JsonSerializer.Deserialize<OcrConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class AnalyticsConfig
    {
        public static AnalyticsConfig FromJson(string json) => JsonSerializer.Deserialize<AnalyticsConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class ClassifierConfig
    {
        public static ClassifierConfig FromJson(string json) => JsonSerializer.Deserialize<ClassifierConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class AutoFocus
    {
        public static AutoFocus FromJson(string json) => JsonSerializer.Deserialize<AutoFocus>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class StreamConfig
    {
        public static StreamConfig FromJson(string json) => JsonSerializer.Deserialize<StreamConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class Misc
    {
        public static Misc FromJson(string json) => JsonSerializer.Deserialize<Misc>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class MiscVolatile
    {
        public static MiscVolatile FromJson(string json) => JsonSerializer.Deserialize<MiscVolatile>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class ItscamproConfig
    {
        public static ItscamproConfig FromJson(string json) => JsonSerializer.Deserialize<ItscamproConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class ItscamproStatus
    {
        public static ItscamproStatus FromJson(string json) => JsonSerializer.Deserialize<ItscamproStatus>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class ImageSignConfig
    {
        public static ImageSignConfig FromJson(string json) => JsonSerializer.Deserialize<ImageSignConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class FtpConfig
    {
        public static FtpConfig FromJson(string json) => JsonSerializer.Deserialize<FtpConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class LinceConfig
    {
        public static LinceConfig FromJson(string json) => JsonSerializer.Deserialize<LinceConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class LinceStatus
    {
        public static LinceStatus FromJson(string json) => JsonSerializer.Deserialize<LinceStatus>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class VehicleIndicatorConfig
    {
        public static VehicleIndicatorConfig FromJson(string json) => JsonSerializer.Deserialize<VehicleIndicatorConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class ProtocolsConfig
    {
        public static ProtocolsConfig FromJson(string json) => JsonSerializer.Deserialize<ProtocolsConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class ProfileTransitioner
    {
        public static ProfileTransitioner FromJson(string json) => JsonSerializer.Deserialize<ProfileTransitioner>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class LanesConfig
    {
        public static LanesConfig FromJson(string json) => JsonSerializer.Deserialize<LanesConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class IoConfig
    {
        public static IoConfig FromJson(string json) => JsonSerializer.Deserialize<IoConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class IoBasic
    {
        public static IoBasic FromJson(string json) => JsonSerializer.Deserialize<IoBasic>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class RestApiClientConfig
    {
        public static RestApiClientConfig FromJson(string json) => JsonSerializer.Deserialize<RestApiClientConfig>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class RestApiClientStatus
    {
        public static RestApiClientStatus FromJson(string json) => JsonSerializer.Deserialize<RestApiClientStatus>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public partial class Licenses
    {
        public static Licenses FromJson(string json) => JsonSerializer.Deserialize<Licenses>(json, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ProfileConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this OcrConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this AnalyticsConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this ClassifierConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this AutoFocus self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this StreamConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this Misc self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this MiscVolatile self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this ItscamproConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this ItscamproStatus self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this ImageSignConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this FtpConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this LinceConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this LinceStatus self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this VehicleIndicatorConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this ProtocolsConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this ProfileTransitioner self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this LanesConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this IoConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this IoBasic self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this RestApiClientConfig self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this RestApiClientStatus self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
        public static string ToJson(this Licenses self) => JsonSerializer.Serialize(self, Pumatronix.Itscam.RestTypes.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                ModeConverter.Singleton,
                TypeEnumConverter.Singleton,
                VariantConverter.Singleton,
                MethodConverter.Singleton,
                SchemeConverter.Singleton,

                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class PurpleMinMaxLengthCheckConverter : JsonConverter<string>
    {
        public override bool CanConvert(Type t) => t == typeof(string);

        public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value.Length <= 256)
            {
                return value;
            }
            throw new Exception("Cannot unmarshal type string");
        }

        public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
        {
            if (value.Length <= 256)
            {
                JsonSerializer.Serialize(writer, value, options);
                return;
            }
            throw new Exception("Cannot marshal type string");
        }

        public static readonly PurpleMinMaxLengthCheckConverter Singleton = new PurpleMinMaxLengthCheckConverter();
    }

    internal class ModeConverter : JsonConverter<Mode>
    {
        public override bool CanConvert(Type t) => t == typeof(Mode);

        public override Mode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "disabled":
                    return Mode.Disabled;
                case "fast":
                    return Mode.Fast;
                case "normal":
                    return Mode.Normal;
                case "slow":
                    return Mode.Slow;
            }
            throw new Exception("Cannot unmarshal type Mode");
        }

        public override void Write(Utf8JsonWriter writer, Mode value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Mode.Disabled:
                    JsonSerializer.Serialize(writer, "disabled", options);
                    return;
                case Mode.Fast:
                    JsonSerializer.Serialize(writer, "fast", options);
                    return;
                case Mode.Normal:
                    JsonSerializer.Serialize(writer, "normal", options);
                    return;
                case Mode.Slow:
                    JsonSerializer.Serialize(writer, "slow", options);
                    return;
            }
            throw new Exception("Cannot marshal type Mode");
        }

        public static readonly ModeConverter Singleton = new ModeConverter();
    }

    internal class FluffyMinMaxLengthCheckConverter : JsonConverter<string>
    {
        public override bool CanConvert(Type t) => t == typeof(string);

        public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value.Length >= 3 && value.Length <= 32)
            {
                return value;
            }
            throw new Exception("Cannot unmarshal type string");
        }

        public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
        {
            if (value.Length >= 3 && value.Length <= 32)
            {
                JsonSerializer.Serialize(writer, value, options);
                return;
            }
            throw new Exception("Cannot marshal type string");
        }

        public static readonly FluffyMinMaxLengthCheckConverter Singleton = new FluffyMinMaxLengthCheckConverter();
    }

    internal class TentacledMinMaxLengthCheckConverter : JsonConverter<string>
    {
        public override bool CanConvert(Type t) => t == typeof(string);

        public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value.Length >= 4 && value.Length <= 32)
            {
                return value;
            }
            throw new Exception("Cannot unmarshal type string");
        }

        public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
        {
            if (value.Length >= 4 && value.Length <= 32)
            {
                JsonSerializer.Serialize(writer, value, options);
                return;
            }
            throw new Exception("Cannot marshal type string");
        }

        public static readonly TentacledMinMaxLengthCheckConverter Singleton = new TentacledMinMaxLengthCheckConverter();
    }

    internal class TypeEnumConverter : JsonConverter<TypeEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum);

        public override TypeEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value == "json")
            {
                return TypeEnum.Json;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void Write(Utf8JsonWriter writer, TypeEnum value, JsonSerializerOptions options)
        {
            if (value == TypeEnum.Json)
            {
                JsonSerializer.Serialize(writer, "json", options);
                return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }

    internal class VariantConverter : JsonConverter<Variant>
    {
        public override bool CanConvert(Type t) => t == typeof(Variant);

        public override Variant Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "multipart":
                    return Variant.Multipart;
                case "singlepart":
                    return Variant.Singlepart;
            }
            throw new Exception("Cannot unmarshal type Variant");
        }

        public override void Write(Utf8JsonWriter writer, Variant value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Variant.Multipart:
                    JsonSerializer.Serialize(writer, "multipart", options);
                    return;
                case Variant.Singlepart:
                    JsonSerializer.Serialize(writer, "singlepart", options);
                    return;
            }
            throw new Exception("Cannot marshal type Variant");
        }

        public static readonly VariantConverter Singleton = new VariantConverter();
    }

    internal class MethodConverter : JsonConverter<Method>
    {
        public override bool CanConvert(Type t) => t == typeof(Method);

        public override Method Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "get":
                    return Method.Get;
                case "post":
                    return Method.Post;
                case "put":
                    return Method.Put;
            }
            throw new Exception("Cannot unmarshal type Method");
        }

        public override void Write(Utf8JsonWriter writer, Method value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Method.Get:
                    JsonSerializer.Serialize(writer, "get", options);
                    return;
                case Method.Post:
                    JsonSerializer.Serialize(writer, "post", options);
                    return;
                case Method.Put:
                    JsonSerializer.Serialize(writer, "put", options);
                    return;
            }
            throw new Exception("Cannot marshal type Method");
        }

        public static readonly MethodConverter Singleton = new MethodConverter();
    }

    internal class SchemeConverter : JsonConverter<Scheme>
    {
        public override bool CanConvert(Type t) => t == typeof(Scheme);

        public override Scheme Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "http":
                    return Scheme.Http;
                case "https":
                    return Scheme.Https;
            }
            throw new Exception("Cannot unmarshal type Scheme");
        }

        public override void Write(Utf8JsonWriter writer, Scheme value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Scheme.Http:
                    JsonSerializer.Serialize(writer, "http", options);
                    return;
                case Scheme.Https:
                    JsonSerializer.Serialize(writer, "https", options);
                    return;
            }
            throw new Exception("Cannot marshal type Scheme");
        }

        public static readonly SchemeConverter Singleton = new SchemeConverter();
    }
    
    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
