#!/usr/bin/env bash
#
# Produce a versioned npm tarball without leaving package.json dirty.
# Reads npmVersion from VERSION.json (generated by make version).
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
NODEJS_DIR="$ROOT/src/wrappers/nodejs"
VERSION_JSON="$ROOT/VERSION.json"

if [[ ! -f "$VERSION_JSON" ]]; then
    echo "npm-pack-versioned: missing VERSION.json (run 'make version' first)" >&2
    exit 1
fi

NPM_VERSION="$(python3 -c "import json, sys; print(json.load(open(sys.argv[1]))['npmVersion'])" "$VERSION_JSON")"

cd "$NODEJS_DIR"

restore_package_json() {
    if [[ -f package.json.bak ]]; then
        mv -f package.json.bak package.json
    fi
}
trap restore_package_json EXIT

cp package.json package.json.bak

python3 - "$NPM_VERSION" <<'PY'
import re
import sys
from pathlib import Path

version = sys.argv[1]
path = Path("package.json")
text = path.read_text(encoding="utf-8")
new_text, count = re.subn(
    r'("version"\s*:\s*)"[^"]*"',
    f'\\1"{version}"',
    text,
    count=1,
)
if count == 0:
    raise SystemExit("npm-pack-versioned: no version field in package.json")
path.write_text(new_text, encoding="utf-8")
PY

npm pack --no-audit --no-fund
