// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAutoSave() {
  return window['go']['main']['App']['GetAutoSave']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetDeviceInfo() {
  return window['go']['main']['App']['GetDeviceInfo']();
}

export function GetSaveDirectory() {
  return window['go']['main']['App']['GetSaveDirectory']();
}

export function GetSubscriptionConfig() {
  return window['go']['main']['App']['GetSubscriptionConfig']();
}

export function RequestSnapshot() {
  return window['go']['main']['App']['RequestSnapshot']();
}

export function SaveFrameToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFrameToFile'](arg1, arg2);
}

export function SelectSaveDirectory() {
  return window['go']['main']['App']['SelectSaveDirectory']();
}

export function SetAutoSave(arg1) {
  return window['go']['main']['App']['SetAutoSave'](arg1);
}

export function SetSaveDirectory(arg1) {
  return window['go']['main']['App']['SetSaveDirectory'](arg1);
}

export function Subscribe() {
  return window['go']['main']['App']['Subscribe']();
}

export function SubscribeWithConfig(arg1) {
  return window['go']['main']['App']['SubscribeWithConfig'](arg1);
}

export function TriggerCapture(arg1) {
  return window['go']['main']['App']['TriggerCapture'](arg1);
}

export function Unsubscribe() {
  return window['go']['main']['App']['Unsubscribe']();
}
